sudo: required
language: javascript
services:
  - docker
before_install:
  - docker build -t amitchawla/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true amitchawla/docker-react npm run test -- --coverage
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "react-docker"
#   env: "Reactdocker-env"
#   bucket_name: "elasticbeanstalk-us-east-1-902970656232"
#   bucket_path: "react-docker"
#   on:
#     branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key:
#       secure: $AWS_SECRET_KEY
