version: "3"
services:
  web:
    image: amitchawla/reactweb:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]
